### ISSUE TITLE
Modify the OnAllStoriedEnd function

### ISSUE THREAD

**Issue by quavo19** [AbdullahAnsarii/rn-story#3]
hello @AbdullahAnsarii please, there's a feature I want to add, I want the onAllStoriesEnd  function to move to the next user stories. it says in the readme that I have to update the index but I don't know which index to update. and I was hoping if you could help. it would make my work easier, thank you.

**Comment by AbdullahAnsarii** [comment]
In order to achieve this functionality, create a state with multiple users stories called `data` and one more state which keeps track of the current story index called `currentStoryIndex` which is being shown for the first story it would be `0` and whenever the `onAllStoriesEnd` you can just simply increment the `currentStoryIndex` to let's say `1` and so on until the length of the `data` array is exhausted.

**Comment by quavo19** [comment]
hello @AbdullahAnsarii i did what was required, 
i setup my state for the data, 
```
const [data, setData] = useState<Data[]>([
    {
      profileImage:
        'https://shorturl.at/fhUV1',
      profileName: 'Abdullah Ansari',
      viewed: false,
      id: 1,
      stories: [
        {
          media: 'https://shorturl.at/mpwQ1',
          mediaType: 'image',
          seeMoreUrl: 'https://abdullahansari.me'
        },
         ]
    },
    {
      profileImage:
        'https://shorturl.at/fhUV1',
      profileName: 'donald',
      viewed: false,
      id: 2,
      stories: [
        {
          media: 'https://shorturl.at/jpJ58',
          mediaType: 'image',
          // duration: 12000
        },
      ]
    },
```
and then my currentStoryIndex state
```
  const [currentStoryIndex, setCurrentStoryIndex] = useState<number | null>(null);
```
and i made a function to update the index of the currentStoryIndex like this 
```
const handleAllStoriesEnd = () => {
    if (currentStoryIndex === null) {
      setCurrentStoryIndex(0); // Start showing the first story
    } else if (currentStoryIndex < data.length - 1) {
      setCurrentStoryIndex(currentStoryIndex + 1); 
    } else {
      setCurrentStoryIndex(null); 
    }
  };
```
then i called the function to be invoked onAllStoruesEnd, like this 
```
 onAllStoriesEnd={handleAllStoriesEnd}
```
but it doesnt move to the next user when the stories end, it just pauses. but if i play the last user, i see the story view closes onAllStoriesEnd, so i know the function works.
even if i try to set the index manually by saying
```
 onAllStoriesEnd={setCurrentStoryIndex(1)}
```
it still pauses onAllStoriesEnd

i would really appreciate your support to move forward. 
thank you
